export const routes = {
  marketing: {
    home: "/",
    pricing: "/pricing",
  },
  auth: {
    login: "/login",
    signup: "/signup",
    verifyEmail: "/verify-email",
    forgotPassword: "/forgot-password",
    resetPassword: "/reset-password",
  },
  app: {
    dashboard: "/dashboard",
    users: "/dashboard/users",
    organizations: "/dashboard/organizations",
    subscriptions: "/dashboard/subscriptions",
    billing: "/dashboard/billing",
    team: "/dashboard/team",
    roles: "/dashboard/roles",
    sessions: "/dashboard/sessions",
    settings: "/dashboard/settings",
    settingsProfile: "/dashboard/settings/profile",
    settingsAuthentication: "/dashboard/settings/authentication",
    settingsSecurity: "/dashboard/settings/security",
    settingsAppearance: "/dashboard/settings/appearance",
    settingsNotifications: "/dashboard/settings/notifications",
    settingsDisplay: "/dashboard/settings/display",
  },
} as const;
